services:


# Container Python
  backend:
    build: ./backend # Cerca il Dockerfile nella cartella backend
    container_name: wedding-backend
    restart: always
    ports:
      - "8000:8000" # da commentare 
    volumes:
      - ./backend/wedding_data:/app/backend/wedding_data



  frontend:
    image: nginx:alpine
    container_name: wedding-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
    # Mappiamo la build di Flutter dentro Nginx
    - ./flutter/build/web:/usr/share/nginx/html:ro
    # Mappiamo la nuova config di Nginx
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # volumes:
    #   - ./frontend:/usr/share/nginx/html:ro
    #   - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend # Nginx parte solo dopo il backend

